### ISSUE TITLE
URLs with an extension are not recognized

### ISSUE THREAD

**Issue by nautilebleu** [lukechilds/my-name-is-url#18]
Urls such as 

- https://msdn.microsoft.com/fr-fr/library/windows/apps/br229576.aspx
- https://www.cdiscount.com/n-380205/cdiscount-immobilier/immobilier-neuf.html

are not recognized. I've done a small fix on a fork

https://github.com/nautilebleu/my-name-is-url

**Comment by lukechilds** [comment]
Brilliant, thanks!

Could you add a test for this functionality to prevent regressions too?

**Comment by lukechilds** [comment]
Closed via https://github.com/lukechilds/my-name-is-url/pull/19
